POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(host ssh dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs background_jobs time)
POWERLEVEL9K_STATUS_HIDE_SIGNAME=true
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_TIME_BACKGROUND='grey85'
POWERLEVEL9K_TIME_FOREGROUND='grey11'
POWERLEVEL9K_HOST_LOCAL_BACKGROUND='237'
POWERLEVEL9K_DIR_HOME_BACKGROUND='111'
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND='111'
POWERLEVEL9K_DIR_ETC_BACKGROUND='111'
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND='111'

source $BEDROCK_DIR/vendor/powerlevel9k/powerlevel9k.zsh-theme
